# Week 3: Further data manipulation

Import packages

In [1]:

import pandas as pd
import numpy as np

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Last week

In [10]:
print("Hellow World"2)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (241319296.py, line 1)

Import our data

In [3]:
df = pd.read_csv('/Users/matthew/ONS/intro_to_python/2011.csv', header = 1)

In [4]:
df.head(2)

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
1,7394745,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3

Using and to combine something we previously did in two lines

In [5]:
df_students = df[df['Student'] == 1]

In [6]:
df_widowed_students = df_students[df_students['Marital Status'] == 5]

In [7]:
df_widowed_students.shape[0]

109

On one line

In [8]:
df_widowed_students_two = df[(df['Student'] == 1) & (df['Marital Status'] == 5)]

In [9]:
df_widowed_students_two.shape[0]

109

Which do you like better? 
The brackets above are used in exactly the same way that you would use brackets in normal math - just saying calculate this first, nothing to do with a tuple, no commas.

# This week

## More on describing datasets

In [11]:
df.describe(include = 'all')

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
count,5.697410e+05,569741,569741,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000
unique,NaN,10,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,E12000008,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,88084,559087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,7.679353e+06,NaN,NaN,2.011870,1.018731,1.507550,3.978680,1.856201,1.777904,1.016239,1.658324,1.191250,2.419387,0.685597,1.240994,2.459844,-3.487095,0.034130
std,1.644702e+05,NaN,NaN,2.358788,0.159058,0.499943,2.219494,1.125020,0.415655,1.153095,1.486598,1.391858,2.493064,5.265465,6.521825,7.398945,5.887539,4.862672
min,7.394483e+06,NaN,NaN,-9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,7.536918e+06,NaN,NaN,2.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,1.000000
50%,7.679353e+06,NaN,NaN,2.000000,1.000000,2.000000,4.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,1.000000,3.000000,4.000000,-9.000000,2.000000
75%,7.821788e+06,NaN,NaN,3.000000,1.000000,2.000000,6.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,5.000000,6.000000,8.000000,3.000000,3.000000
max,7.964223e+06,NaN,NaN,6.000000,3.000000,2.000000,8.000000,5.000000,2.000000,2.000000,5.000000,5.000000,9.000000,9.000000,9.000000,12.000000,4.000000,4.000000

In [12]:
df.mode() # similar to "top" above but relavant to more columms

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,7959238,E12000008,H,2,1,2,1,1,2,1,1,1,2,1,-9,-9,-9,2

## Applying a function to a whole column

In [13]:
# Last week we spoke about changing column names using something called list comprehnsion
# df.columns = [col.lower() for col in list(df.columns)] 
# Thankfully applying  functions to every element in a dataframe column is way easier 

# Remember for strings we do x.function()
# for other types we normaly do function(x)

In [14]:
df['Region'] = df['Region'].str.lower() # have to tell pandas that its a string, its normally just a pointer to a string

In [15]:
df.head(2)

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,7394816,e12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
1,7394745,e12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3

In [16]:
df['Region'] = df['Region'].str.upper()

In [17]:
df.head(2)

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
0,7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
1,7394745,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3

In [18]:
df['sqrt_age'] = df['Age'].apply(np.sqrt)

In [19]:
df.head(2)

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade,sqrt_age
0,7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4,2.44949
1,7394745,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3,2.00000

## Combining columns

In [20]:
df['age_student'] = df['Age']*df['Student']

In [21]:
df.head()

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade,sqrt_age,age_student
0,7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4,2.449490,12
1,7394745,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3,2.000000,8
2,7395066,E12000001,H,3,1,2,4,1,2,1,1,1,1,1,6,11,3,4,2.000000,8
3,7395329,E12000001,H,3,1,2,2,1,2,1,2,1,2,1,7,7,3,2,1.414214,4
4,7394712,E12000001,H,3,1,1,5,4,2,1,1,1,2,1,1,4,3,2,2.236068,10

## Dictionaries

Looking at a new type, a dictionary. Curley brackets with key: value pairs, each pair seperated by a comma

In [22]:
region_dict = {'E12000001': 'North East', 
'E12000002': 'North West', 
'E12000003': 'Yorkshire and the Humber', 
'E12000004': 'East Midlands', 
'E12000005': 'West Midlands', 
'E12000006': 'East of England', 
'E12000007': 'London', 
'E12000008': 'South East', 
'E12000009': 'South West',
'W92000004': 'Wales'}

In [23]:
type(region_dict)

dict

In [ ]:
religion_dict = {1: 'No religion', 
2: 'Christian', 
3: 'Buddhist', 
4: 'Hindu', 
5: 'Jewish', 
6: 'Muslim', 
7: 'Sikh', 
8: 'Other religion', 
9: 'Not stated',
-9: 'No code required'}

In [25]:
type(religion_dict) # integers can be keys

dict

In [26]:
religion_dict[-9]

'No code required'

In [27]:
eco_dict = {1 : "Active: Employee", 
                 2 : "Active: Self-employed", 
                 3 : "Active: Unemployed", 
                 4 : "Active: Full-time student",
                 5 : "Inactive: Retired", 
                 6 : "Inactive: Student", 
                 7 : "Inactive: Looking after home", 
                 8 : "Inactive: Disabled",
                 9 : "Inactive: Other",
                 -9: "No code required"}

## Using a dictionary to change a column

You cant use map with indexes

In [28]:
df['Region'] = df['Region'].map(region_dict)

In [29]:
df.head(2)

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade,sqrt_age,age_student
0,7394816,North East,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4,2.44949,12
1,7394745,North East,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3,2.00000,8

## Is female

In [30]:
e = True
type(e)

bool

I want to build the group up to feeling confident writing code yourself. 
Question: Can you write some python code that makes a new column called something like "is_female" in the dataframe which has a value of True if the person is Female and a value of False if the person is Male? 
Break it down: First use the variables list to make a dictionary. What are the key-value pairs? Then use .map to make a new column. 
Remember in the 2011 Census we coded female as 2 and Male as 1

In [31]:
sex_dict = {1:False, 2:True}

In [32]:
df['Female'] = df['Sex'].map(sex_dict)

# Week 4