# Week 2

In [1]:
# comment

In [2]:
a = 1

In [3]:
a

1

In [5]:
name = 'michaela   '

In [6]:
name = name.strip()

In [8]:
name

'michaela'

In [9]:
name = name.capitalize()

In [10]:
name

'Michaela'

In [11]:
type(name)

str

In [12]:
type(a)

int

In [13]:
# b = 2

In [20]:
import pandas as pd

In [23]:
df = pd.read_csv('2011.csv', header = 1, index_col = "Person ID")

In [24]:
df.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
Person ID,,,,,,,,,,,,,,,,,
7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,4
7394745,E12000001,H,5,1,1,4,1,2,1,1,1,2,1,8,6,4,3
7395066,E12000001,H,3,1,2,4,1,2,1,1,1,1,1,6,11,3,4
7395329,E12000001,H,3,1,2,2,1,2,1,2,1,2,1,7,7,3,2
7394712,E12000001,H,3,1,1,5,4,2,1,1,1,2,1,1,4,3,2

In [25]:
df.tail()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
Person ID,,,,,,,,,,,,,,,,,
7946020,W92000004,H,1,1,1,5,1,2,1,4,1,9,1,8,8,3,3
7944310,W92000004,H,3,1,1,3,1,2,1,2,1,1,1,7,4,3,4
7945374,W92000004,H,3,1,1,1,1,1,1,1,1,2,-9,-9,-9,-9,-9
7944768,W92000004,H,1,1,2,8,5,2,1,3,1,9,5,9,2,-9,4
7944959,W92000004,H,2,1,2,2,2,2,1,2,1,1,1,7,4,1,4

In [26]:
type(df)

pandas.core.frame.DataFrame

In [27]:
df.dtypes

Region                       object
Residence Type               object
Family Composition            int64
Population Base               int64
Sex                           int64
Age                           int64
Marital Status                int64
Student                       int64
Country of Birth              int64
Health                        int64
Ethnic Group                  int64
Religion                      int64
Economic Activity             int64
Occupation                    int64
Industry                      int64
Hours worked per week         int64
Approximated Social Grade     int64
dtype: object

In [28]:
df.shape

(569741, 17)

In [30]:
df.describe(include = 'all')

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
count,569741,569741,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000,569741.000000
unique,10,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,E12000008,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,88084,559087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2.011870,1.018731,1.507550,3.978680,1.856201,1.777904,1.016239,1.658324,1.191250,2.419387,0.685597,1.240994,2.459844,-3.487095,0.034130
std,NaN,NaN,2.358788,0.159058,0.499943,2.219494,1.125020,0.415655,1.153095,1.486598,1.391858,2.493064,5.265465,6.521825,7.398945,5.887539,4.862672
min,NaN,NaN,-9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,NaN,NaN,2.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-9.000000,-9.000000,-9.000000,1.000000
50%,NaN,NaN,2.000000,1.000000,2.000000,4.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,1.000000,3.000000,4.000000,-9.000000,2.000000
75%,NaN,NaN,3.000000,1.000000,2.000000,6.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,5.000000,6.000000,8.000000,3.000000,3.000000
max,NaN,NaN,6.000000,3.000000,2.000000,8.000000,5.000000,2.000000,2.000000,5.000000,5.000000,9.000000,9.000000,9.000000,12.000000,4.000000,4.000000

In [31]:
df.columns

Index(['Region', 'Residence Type', 'Family Composition', 'Population Base',
       'Sex', 'Age', 'Marital Status', 'Student', 'Country of Birth', 'Health',
       'Ethnic Group', 'Religion', 'Economic Activity', 'Occupation',
       'Industry', 'Hours worked per week', 'Approximated Social Grade'],
      dtype='object')

In [32]:
type(df.columns)

pandas.core.indexes.base.Index

In [33]:
student_column = df['Student']

In [34]:
student_column

Person ID
7394816    2
7394745    2
7395066    2
7395329    2
7394712    2
          ..
7946020    2
7944310    2
7945374    1
7944768    2
7944959    2
Name: Student, Length: 569741, dtype: int64

In [ ]:
# ==, >, >=, <, <=, !=

In [35]:
students = df[df['Student'] == 1]

In [36]:
students.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,Approximated Social Grade
Person ID,,,,,,,,,,,,,,,,,
7394711,E12000001,H,2,1,1,1,1,1,1,1,1,1,-9,-9,-9,-9,-9
7394869,E12000001,H,1,1,2,2,1,1,1,2,1,1,4,-9,-9,-9,2
7395019,E12000001,H,1,1,2,2,1,1,1,2,1,1,4,7,6,-9,2
7394933,E12000001,H,3,1,1,2,1,1,1,1,1,1,6,-9,-9,-9,2
7394875,E12000001,H,2,1,1,1,1,1,1,1,1,2,-9,-9,-9,-9,-9

In [37]:
students.shape

(126537, 17)

In [38]:
type(students.shape)

tuple

In [39]:
df.shape[0]

569741

In [43]:
students.shape[0]/df.shape[0]

0.2220956539901464

In [50]:
str(round(students.shape[0]/df.shape[0], 2)*100) + '%'

'22.0%'

In [51]:
widowed_students = students[students['Marital Status'] == 5]

In [52]:
widowed_students.shape

(109, 17)

In [53]:
widowed_students.shape[0]/df.shape[0]

0.00019131500102678234

In [54]:
students['Marital Status'] == 5

Person ID
7394711    False
7394869    False
7395019    False
7394933    False
7394875    False
           ...
7946548    False
7944917    False
7946558    False
7944370    False
7945374    False
Name: Marital Status, Length: 126537, dtype: bool

In [55]:
widowed_students.to_csv('widowed_students.csv')